name: glm_4_6v_flash
path: zai-org/GLM-4.6V-Flash
mode: eval
model_dtype: fp32
amp_dtype: bf16
task: aesthetic  # "aesthetic" or "text_rendering"

fsdp:
  fsdp_strategy: full_shard
  fsdp_cpu_offload: false

eval:
  eval_batch_size: 2
