name: qwen3_5_27b
path: Qwen/Qwen3.5-27B
mode: eval
model_dtype: fp32
amp_dtype: bf16
task: aesthetic  # "aesthetic" or "text_rendering"

fsdp:
  fsdp_strategy: full_shard
  fsdp_cpu_offload: false

eval:
  eval_batch_size: 1
