name: qwen3_vl_32b
path: Qwen/Qwen3-VL-32B-Instruct
mode: eval
model_dtype: fp32
amp_dtype: bf16
task: aesthetic  # "aesthetic" or "text_rendering"

fsdp:
  fsdp_strategy: full_shard
  fsdp_cpu_offload: false

eval:
  eval_batch_size: 1
