name: qwen3_5_9b
path: Qwen/Qwen3.5-9B
mode: eval
model_dtype: fp32
amp_dtype: bf16
task: aesthetic

fsdp:
  fsdp_strategy: full_shard
  fsdp_cpu_offload: false

eval:
  eval_batch_size: 1
