defaults:
  - _base_
  - _self_
  - data: hpd_v2_benchmark
  - model: flux
  - reward_model: hps_v2  # evaluation model

common:
  cache_log_dir: ""  # resume evaluation
  batch_eval_root: ""  # root directory to scan for model.pt (batch eval mode)

log:
  result_dir: inference_results  # dir to save inference results

name: evaluation
